#C:\MaestroLite Data\Micross Sub Utilities Rotary https://protect-us.mimecast.com/s/4z38Co2XX2tEKKKf6JV3a?domain=crewe.nc
(M98 PPUMP2START
(M98 PLOAD
(Initialization Complete )
G52 X0 Y0 Z0 B0 (Calibration Offsets)
 

(***********************DECLAIR VARIABLES HERE********************************
(******************************TRAY*******************************************
REAL #TRAY_PICK_Z
REAL #TRAY_PICK_X
REAL #TRAY_PICK_PAUSE
REAL #TRAY_PITCH 
REAL #TRAY_DROP_HEIGHT
REAL #VACUUM_BREAK_DISTANCE
INTEGER #NUMBER_PICKS
INTEGER #NUMBER_HEADS
INTEGER #START_OF_TRAY_FLAG
(*****************************FLUX********************************************
REAL #FLUX_HEIGHT_X
REAL #FLUX_HEIGHT_Y
REAL #FLUX_ROTATE_ANGLE
REAL #FLUX_DIP_ANGLE
REAL #FLUX_DIP_ANGLE_LHS
REAL #FLUX_DWELL
REAL #FLUX_ANGLE_RESIDUE
REAL #FLUX_DIP_IN_SPEED
REAL #FLUX_DIP_DEPTH
REAL #FLUX_DIP_OUT_SPEED
REAL #FLUX_TYPE
STRING #FLUX_DIP_MODE
REAL #FLUX_OFFSET
STRING #FLUX_USED
REAL #DEGREES_ROTATE_FLUX
REAL #NUMBER_ROTATIONS_FLUX
(*****************************PRE-HEAT****************************************
INTEGER #NUMBER_OF_PREHEAT_OSCILLATIONS
REAL #PRE_HEAT_HEIGHT
REAL #PRE_HEAT_OFFSET
STRING #PRE_HEAT_USED
(*****************************COMPONENT SIZE**********************************
REAL #PART_SIZE_X
REAL #PART_SIZE_Y
REAL #NUMBER_OF_SIDES
(*****************************SOLDER DIP**************************************
REAL #SOLDER_HEIGHT_X
REAL #SOLDER_HEIGHT_Y
REAL #SOLDER_WAVE_HEIGHT
REAL #SCAVENGER_HEIGHT_X
REAL #SCAVENGER_HEIGHT_Y
REAL #SOLDER_ROTATE_ANGLE
REAL #SOLDER_DIP_ANGLE
REAL #SOLDER_DIP_ANGLE_LHS
REAL #SOLDER_DWELL
REAL #SOLDER_ANGLE_RESIDUE
REAL #SOLDER_DIP_IN_SPEED
REAL #SOLDER_DIP_DEPTH
REAL #SOLDER_DIP_OUT_SPEED
STRING #SOLDER_TYPE
STRING #SOLDER_POT_TYPE
REAL #SOLDER_OFFSET
REAL #SOLDER_HOLD_HEIGHT
STRING #SCAVENGER_USED
INTEGER #NUMBER_DIPS
INTEGER #NUMBER_DIPS_STORE
REAL #SOLDER_ANGLE_OFFSET
(*******************************WASH******************************************
REAL #WASH_HEIGHT
REAL #WASH_DIP_DEPTH
REAL #WASH_DIP_ANGLE
REAL #WASH_DIP_ANGLE_LHS
REAL #NUMBER_ROTATIONS_WASH
REAL #DEGREES_ROTATE_WASH
REAL #WASH_IN_OUT_SPEED
STRING #WASH_USED
(*******************************DRY*******************************************
REAL #DRY_HEIGHT
REAL #NUMBER_ROTATIONS_DRY
REAL #DEGREES_ROTATE_DRY
STRING #DRY_USED
STRING #AIRKNIFE_UP
(************************OPERATOR ENTER DATA HERE*****************************
(*******************************TRAY******************************************
#TRAY_PICK_Z= -89.9
#TRAY_PICK_X= 145.3   (POSITION OF CENTRE OF FIRST ROW OF DEVICES
#TRAY_PITCH= 42.48
#TRAY_PICK_PAUSE= 2      (THIS PAUSE ALLOWS A VACUUM TO BE PULLED
#NUMBER_PICKS= 4   
#NUMBER_HEADS= 4        ( ENTER EITHER 8 OR 4, IF 4 IS SELECTED THEN THE RHS SET OF HEADS ARE USED ONLY
#TRAY_DROP_HEIGHT= 0.5    (DROP HEIGHT IS HEIGHT ABOVE TRAY PICK HEIGHT VALUE
#VACUUM_BREAK_DISTANCE= 5  (DISTANCE TRAVELLED FROM THE DROP POSITION TO BREAK THE VACUUM
(*******************************COMPONENT***************************************
#NUMBER_OF_SIDES= 4        (ENTER 2 OR 4 FOR THE NUMBER OF COMPONENT SIDES TO DIP, 2 SIDES WILL ALWAYS DIP THE X DIRECTION SIDES
(*******************************FLUX********************************************
#FLUX_HEIGHT_X= -67         ( ONLY THIS VALUE IS USED FOR THE ROTARY FLUX DEPTH
#FLUX_HEIGHT_Y= -67
#FLUX_ROTATE_ANGLE= 0         (ANGLE OF THE DEVICE TO WITHDRAW FROM THE FLUX
#FLUX_DIP_ANGLE= -30          (ANGLE OF THE HEAD TO THE FLUX
#FLUX_DWELL= 0
#FLUX_DIP_IN_SPEED= 6000
#FLUX_DIP_DEPTH= 4.9
#FLUX_DIP_OUT_SPEED= 6000
#FLUX_DIP_MODE= "ROTATE"    ( ENTER DIP OR ROTATE
#NUMBER_ROTATIONS_FLUX= 1
#FLUX_TYPE= 1			(ENTER 1 OR 2 FOR THE FLUX REQUIRED
#FLUX_USED= "YES"		(ENTER YES OR NO
(*******************************PRE-HEAT***************************************
#PRE_HEAT_USED= "YES"     (ENTER YES OR NO
#NUMBER_OF_PREHEAT_OSCILLATIONS= 25
#PRE_HEAT_HEIGHT= -86
#PRE_HEAT_OFFSET= 525    (HEAD CENTRES BOTH SIDES ON HEATER AT 591
(*******************************COMPONENT SIZE*********************************
#PART_SIZE_X= 27
#PART_SIZE_Y= 27
(*******************************SOLDER DIP*************************************
#SOLDER_HEIGHT_X= 38.3         (- VALUES FOR FLAT POT, + VALUES FOR WAVE
#SOLDER_HEIGHT_Y= 38.3        (- VALUES FOR FLAT POT, + VALUES FOR WAVE
#SOLDER_WAVE_HEIGHT= -31.3
#SCAVENGER_HEIGHT_X= 0
#SCAVENGER_HEIGHT_Y= 0
#SOLDER_ROTATE_ANGLE= 5     (ANGLE OF THE DEVICE TO WITHDRAW FROM THE SOLDER
#SOLDER_DIP_ANGLE= 0        (ANGLE OF THE HEAD TO THE SOLDER
#SOLDER_DWELL= 2
#SOLDER_DIP_IN_SPEED= 800
#SOLDER_DIP_DEPTH= 4.5
#SOLDER_DIP_OUT_SPEED= 90
#SOLDER_TYPE= "LEAD"			(ENTER LEAD OR LEADFREE
#SOLDER_POT_TYPE= "WAVE"                (ENTER FLAT OR WAVE
#SOLDER_HOLD_HEIGHT= 6.5
#NUMBER_DIPS= 1              (NUMBER OF TIMES THE PART IS PROCESSED 
#SCAVENGER_USED= "NO"   (ENTER YES OR NO
(*******************************WASH******************************************
#WASH_HEIGHT= -66
#WASH_DIP_DEPTH= 8
#WASH_DIP_ANGLE= -26
#NUMBER_ROTATIONS_WASH= 10
#WASH_IN_OUT_SPEED= 6000
#WASH_USED= "YES"  ( ENTER YES OR NO 
(*******************************DRY*******************************************
#DRY_HEIGHT= -85
#NUMBER_ROTATIONS_DRY= 11
#DRY_USED= "YES"    (ENTER YES OR NO
#AIRKNIFE_UP= "NO"     (ENTER YES TO USE AIR KNIFE IN UP POSITION, ENTER NO FOR USE IN DOWN POSITION
( ********************** MAIN G-CODE PROCESS POSITION 1*********************** 
IF #NUMBER_OF_SIDES= 2 THEN
#SOLDER_ANGLE_RESIDUE= 180 - #SOLDER_ROTATE_ANGLE
ELSE
#SOLDER_ANGLE_RESIDUE= 90 - #SOLDER_ROTATE_ANGLE
ENDIF
#SOLDER_DIP_ANGLE_LHS= #SOLDER_DIP_ANGLE * -1
#NUMBER_DIPS_STORE= #NUMBER_DIPS

IF #SOLDER_TYPE= "LEADFREE" THEN
#SOLDER_OFFSET= 1630
IF #SOLDER_POT_TYPE= "WAVE" THEN
#SOLDER_OFFSET= 1570  (OFFSET FOR THE SIDEWAVE NOZZLE ON THE LEFT
ENDIF
ELSE
#SOLDER_OFFSET= 2013
IF #SOLDER_POT_TYPE= "WAVE" THEN
#SOLDER_OFFSET= 1962  (OFFSET FOR THE SIDEWAVE NOZZLE ON THE LEFT
ENDIF			
ENDIF
IF #NUMBER_OF_SIDES= 2 THEN
#FLUX_ANGLE_RESIDUE= 180 - #FLUX_ROTATE_ANGLE
ELSE
#FLUX_ANGLE_RESIDUE= 90 - #FLUX_ROTATE_ANGLE
ENDIF
#FLUX_DIP_ANGLE_LHS= #FLUX_DIP_ANGLE * -1



IF #FLUX_TYPE= 1 THEN 
#FLUX_OFFSET= 813 (FOR FLUX POT 1
ELSE
#FLUX_OFFSET= 1010 (FOR FLUX POT 2
ENDIF

#DEGREES_ROTATE_DRY= #NUMBER_ROTATIONS_DRY * 360 (MULTIPLES OF 360 DEGREES ENSURES PARTS ARE PUT BACK IN THE CORRECT DIRECTION ON TRAY
#DEGREES_ROTATE_WASH= #NUMBER_ROTATIONS_WASH * 360 (MULTIPLES OF 360 DEGREES ENSURES PARTS ARE PUT BACK IN THE CORRECT DIRECTION ON TRAY
#DEGREES_ROTATE_FLUX= #NUMBER_ROTATIONS_FLUX * 360 (MULTIPLES OF 360 DEGREES ENSURES PARTS ARE PUT BACK IN THE CORRECT DIRECTION ON TRAY
#WASH_DIP_ANGLE_LHS= #WASH_DIP_ANGLE * -1

#START_OF_TRAY_FLAG= 1

WHILE #NUMBER_PICKS>0 DO		(REPEAT PROCESS FOR THE NUMBER OF PICKS FROM THE TRAY
M98 PPARTLOADROTARY		
G01 X#TRAY_PICK_X F8000
G01 Z#TRAY_PICK_Z F2000
M28                           (TURN VACUUM PICKUP ON)
G04 P#TRAY_PICK_PAUSE
G01 Z-5 F6000                 (RETURN TO PROCESS POSITION)
#NUMBER_DIPS= #NUMBER_DIPS_STORE
WHILE #NUMBER_DIPS>0 DO

IF #FLUX_USED= "YES" THEN
IF #FLUX_DIP_MODE= "DIP" THEN
M98 PPARTFLUX			(MOVE TO FLUX POT
ELSE
M98 PPARTFLUXROTORY			(MOVE TO FLUX POT
ENDIF
ENDIF

M98 PPARTPREHEATROTARY		(MOVE TO PREHEAT STATION	

IF  #SCAVENGER_USED= "YES" THEN
M98 PPARTREMOVEALLOY			(MOVE TO SCAVENGER POT
ENDIF

IF  #SCAVENGER_USED= "YES" THEN
IF #FLUX_USED= "YES" THEN
M98 PPARTFLUX			(MOVE TO FLUX POT
ENDIF
ENDIF

IF  #SCAVENGER_USED= "YES" THEN
M98 PPARTPREHEATROTARY		(MOVE TO PREHEAT STATION	
ENDIF


IF #SOLDER_POT_TYPE= "FLAT" THEN
M98 PSOLDERFLATPOT	  (MOVE TO SOLDER POT
IF #SOLDER_TYPE= "LEADFREE" THEN
M17 M35		(PUMP1 OFF, NITROGEN1 OFF
ELSE
M19 M42 	(PUMP2 OFF, NITROGEN2 OFF
ENDIF
ELSE
M98 PSOLDERSIDEWAVE	  (MOVE TO SOLDER POT
IF #SOLDER_TYPE= "LEADFREE" THEN
M17 M35		(PUMP1 OFF, NITROGEN1 OFF
ELSE
M19 M42 	(PUMP2 OFF, NITROGEN2 OFF
ENDIF
ENDIF

#NUMBER_DIPS= #NUMBER_DIPS-1
ENDWHILE

IF #WASH_USED= "YES" THEN
M98 PPARTWASH
ENDIF

IF #DRY_USED= "YES" THEN
M98 PPARTDRY
ENDIF
 
M98 PPARTUNLOAD			(MOVE TO UNLOAD STATION
G01 X#TRAY_PICK_X
G01 Z#TRAY_PICK_Z+#TRAY_DROP_HEIGHT F6000
M29
G04 P1.0
G91
G01 X-#VACUUM_BREAK_DISTANCE
G90
G01 Z-5 F6000 

#TRAY_PICK_X= #TRAY_PICK_X - #TRAY_PITCH
#NUMBER_PICKS= #NUMBER_PICKS-1
ENDWHILE

G56
M98 PUNLOAD
M30.1
