
#R:\Manufacturing\Robotic Solder\Odyssey Programs\Odyssey #1\SUBROUTINES\ODYSSEY1 NEW PREHEAT SUBROUTINES.nc
M14 (TURNS ON THE PRE-HEAT IDLE)
(*****************************PRE-HEAT****************************************)
REAL #PRE_HEAT_OFFSET
REAL #PRE_HEAT_HEIGHT
STRING  #PRE_HEAT_USED
STRING #SOLDER_TYPE
REAL #NUMBER_HEADS 
(*******************************PRE-HEAT***************************************)
#PRE_HEAT_USED= "YES" (ENTER YES OR NO)
#PRE_HEAT_HEIGHT= -50 (BAR TOOL HEIGHT)
#SOLDER_TYPE = "LEAD" (ENTER "LEAD" OR "LEADFREE") 
#NUMBER_HEADS = 1 (ADDED YM)

#PRE_HEAT_OFFSET= 1399 (ROTARY HEAD CENTERED = 1272)

M98 PPARTPREHEATROTARY (MOVE TO PREHEAT STATION)