(********************** OPERATOR ENTER PARAMETERS HERE ***********************)

#FLUX_HEIGHT= -97.0 		        (SET SO PINS/PADS TOUCH FLUX-SURFACE)
#FLUX_DWELL= 0.6
#FLUX_DRIP_DWELL= 3
#FLUX_DRIP_ANGLE= 40
#FLUX_DIP_SPEED_IN= 2000
#FLUX_DIP_SPEED_OUT= 6000
#FLUX_DIP_DEPTH= 1

(*****************************************************************************)
#PREHEAT_USED= "YES" 	          (ENTER "YES" OR "NO")
#PREHEAT_POSITION = 615
#PREHEAT_HEIGHT= -90
#PREHEAT_DWELL= 45

(*****************************************************************************)
#SOLDER_POT_CHOICE= "LEADFREEDRAG"  (LEAD-FREE SAC305 POT)
#SOLDER_POSITION_PBF = 1900   (LEAD-FREE SOLDER POT X-POSITION)
#SOLDER_HEIGHT_PBF= -80         (LEAD-FREE SOLDER POT NOZZLE HEIGHT, Z-POSITION)
#SPEED_ACROSS_WAVE_PBF= 700     (SPEED ACROSS LEAD-FREE SOLDER WAVE)
#ANGLE_OVER_WAVE_PBF= 0
#PALLETWIDTH= 170               (LOWER PALLETWIDTH ALLOWS FOR HIGHER DRAG ANGLE)

(*********************** END OF OPERATOR DATA INPUT **************************)

M98 PPARTLOAD
G01 X100 Z-5 F4000              (MOVE TOOL HEAD INTO LOAD POSITION)

IF #FLUX_USED= "YES" THEN
M98 PFLUX	                      (MOVE TO FLUX POSITION)
ENDIF

IF #PREHEAT_USED= "YES" THEN
M98 PPREHEAT		                (MOVE TO PREHEAT POSITION)
ENDIF

M98 PPUMP2START                 (TURN ON SOLDER PUMP)
M98 PLEADFREEDRAG		 	          (MOVE TO SOLDER POT AND DIP)


M98 PSOLDERPUMPSTOP             (TURN ON SOLDER PUMP)

M98 PPARTUNLOAD			            (MOVE TO PART UNLOAD POSITION, X=100)
G56                             (SET PROGRAM ZERO AND FIXTURE OFFSETS)
M98 PUNLOAD                     (MOVE TO UNLOAD POSITION, X=1.1)
M30                             (END PROGRAM, RESET)
